name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Build examples
        run: cargo build --examples

      - name: Test crate
        run: cargo test

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
